[package]
name = "wifi-tui"
version = "0.1.0"
edition = "2021"

[dependencies]
zbus = "3"
zvariant = "3"
ratatui = "0.24"
crossterm = "0.27"
tokio = { version = "1", features = ["full"] }
futures = "0.3"
anyhow = "1.0"